---
- name: Terminate EC2 instances
  hosts: tag_Environment_testing
  connection: local
  gather_facts: no

  tasks:


  - name: EC2 Facts
    ec2_instance_facts:
      region: eu-central-1
      filters:
        "tag:Environment": "testing"
    register: ec2
  
  - name: Kill EC2 Instance
    ec2:
      instance_ids: "{{ item.instance_id }}"
      state: 'absent'
      region: eu-central-1
    with_items: "{{ ec2.instances }}"
